### ISSUE TITLE
Issue with version 1.3.6

### ISSUE THREAD

**Issue by privatizer** [kjamison/ZoteRename#3]
The newest version (ZoteRename-1.3.6) does not seem to work with Zotero 5.0.94. The extension can be installed, but none of function can be excuted. Since I haven't found any alternatives, I really hope that the extension will work soon.

**Comment by kjamison** [comment]
Sorry to say I don't really have the bandwidth to maintain this plugin anymore. They seem to have changed some things inside Zotero so that it would require some effort to figure out what's going wrong and how to fix it. The source is available here on github of course, if anyone wants to try. it's not very complicated as code goes. I wouldn't be surprised if most of the features ZoteRename provides are available through other plugins at this point.
